$background = rgb(FDFCF7)
$foreground = rgb(030404)
$color0 = rgb(F2EECB)
$color1 = rgb(107E47)
$color2 = rgb(7C4A2D)
$color3 = rgb(0C5631)
$color4 = rgb(092F1C)
$color5 = rgb(060F0B)
$color6 = rgb(050707)
$color7 = rgb(030404)
$color8 = rgb(A9A78E)
$color9 = rgb(15A85E)
$color10 = rgb(A5623C)
$color11 = rgb(107342)
$color12 = rgb(0C3E25)
$color13 = rgb(08140F)
$color14 = rgb(070909)
$color15 = rgb(010101)

# Original Colors

#$background = rgb(FDFCF7)
#$foreground = rgb(030404)
#$color0 = rgb(F2EECB)
#$color1 = rgb(107E47)
#$color2 = rgb(7C4A2D)
#$color3 = rgb(0C5631)
#$color4 = rgb(092F1C)
#$color5 = rgb(060F0B)
#$color6 = rgb(050707)
#$color7 = rgb(030404)
#$color8 = rgb(A9A78E)
#$color9 = rgb(15A85E)
#$color10 = rgb(A5623C)
#$color11 = rgb(107342)
#$color12 = rgb(0C3E25)
#$color13 = rgb(08140F)
#$color14 = rgb(070909)
#$color15 = rgb(010101)
