#!/usr/bin/env zsh


function load_zsh_plugins {
    # Oh-my-zsh installation path
    zsh_paths=(
        "$HOME/.oh-my-zsh"
        "/usr/local/share/oh-my-zsh"
        "/usr/share/oh-my-zsh"
    )
    for zsh_path in "${zsh_paths[@]}"; do [[ -d $zsh_path ]] && export ZSH=$zsh_path && break; done
    # Load Plugins
    hyde_plugins=(git zsh-256color zsh-autosuggestions zsh-syntax-highlighting)
    plugins+=("${plugins[@]}" "${hyde_plugins[@]}" git zsh-256color zsh-autosuggestions zsh-syntax-highlighting)
    # Deduplicate plugins
    plugins=("${plugins[@]}")
    plugins=($(printf "%s\n" "${plugins[@]}" | sort -u))

    # Loads om-my-zsh
    [[ -r $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh
}
export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/lattice/.local/bin:/home/lattice/.cargo/bin/
export XDG_CONFIG_HOME=~/.config/
HISTORY_IGNORE='(exit|cd|ls|bg|fg|history|vim|nvim|ez|l|la|ll|zel|za)'

# Function to handle initialization errors
function handle_init_error {
    if [[ $? -ne 0 ]]; then
        echo "Error during initialization. Please check your configuration."
    fi
}

function no_such_file_or_directory_handler {
    local red='\e[1;31m' reset='\e[0m'
    printf "${red}zsh: no such file or directory: %s${reset}\n" "$1"
    return 127
}


#if [ -t 1 ]; then
#    # We are loading the prompt on start so users can see the prompt immediately
#    # Powerlevel10k theme path
#    P10k_THEME=${P10k_THEME:-/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme}
#    [[ -r $P10k_THEME ]] && source $P10k_THEME
#
#    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh
#    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
#
#fi
    # Load plugins
    load_zsh_plugins

###### Custom aliases ######
    if [[ -x "$(which eza)" ]]; then
	    alias l='eza -lh --icons=auto' \
	          ls='eza --icons=auto' \
      		  ll='eza -lha --icons=auto --sort=name --group-directories-first' \
      		  exegol='sudo -E /home/lattice/.local/bin/exegol' \
      		  lt='eza --icons=auto --tree' \
      		  cls='clear' \
      		  ff='fastfetch' \
            ipa='ip --brief -4 a' \
            manual='compgen -c | fzf --border | xargs man' \
            yz='yazi' \
	          nv='nvim' \
            wcc='x86_64-w64-mingw32-g++'\
            colors='for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done'\
            labs='sudo echo && sudo openvpn ~/vpn/lab_TLattice.ovpn >/dev/null &' \
            fastcat='bash /home/lattice/extras/FastCat/fastcat.sh --shell' \
            icat='kitten icat' \
            beats='~/extras/Rofi-Beats/RofiBeats.sh' \
            tx='tmux' \
            'cd'='z' \
            zel='zellij' \
            zrf='zellij run --floating --'\
            sko='sudo killall openvpn' \
            wclip='wl-copy' \
            wpaste='wl-paste' \
            ez='exec zsh' \
            update='sudo pacman -Syu'
    fi

    function cmk {
        mkdir -p "$1" && cd "$1"
    }
#######################


#####  ZELLIJ  #####
function za {
  #fzf --query="$1" --height 10% --border=sharp \
 export SESSION=$( 
            zel ls --no-formatting \
          | awk -F '[' '{printf "%s\n", $1}'   \
          | tr -d " "  \
          | gum filter --placeholder "Attach to a zellij session"
         )

 zellij attach $SESSION
}

autoload -Uz add-zsh-hook
preexec_pipe_message_to_zjswitcher() {
    [[ -n "$ZELLIJ" ]] && zellij pipe --name Event::CommandUpdate -- $1
}
add-zsh-hook preexec preexec_pipe_message_to_zjswitcher

precmd_pipe_message_to_zjswitcher() {
    [[ -n "$ZELLIJ" ]] && zellij pipe --name Event::CommandUpdate -- $SHELL
}
add-zsh-hook precmd precmd_pipe_message_to_zjswitcher
############


##### Yazi stuff ######
  function y() {
  	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  	yazi "$@" --cwd-file="$tmp"
  	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
  		builtin cd -- "$cwd"
  	fi
  	rm -f -- "$tmp"
  }
########





######  FZF  ######
zvm_after_init() {
  source /usr/share/fzf/key-bindings.zsh
  source /usr/share/fzf/completion.zsh
}

export FZF_COMPLETION_TRIGGER='::'
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | wl-copy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf "$@" --preview 'tree -C {} | head -200' ;;
    cat|bat|nvim)
      fzf "$@" --preview 'bat --style=numbers --color=always --line-range :500 {}' ;;
    git)
      fzf "$@" --preview 'git diff --color=always {}' ;;
    *)            fzf "$@" ;;
  esac
}
###########




#### keybinds ######
bindkey -r '^x'
bindkey "^b" backward-word
bindkey "^f" forward-word
bindkey "^x" delete-char
#bindkey "^d" delete-word


function zvm_config() {
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
  ZVM_VI_INSERT_ESCAPE_BINDKEY=a\;
}

source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source ~/.zsh-vi-man/zsh-vi-man.plugin.zsh

function zvm_after_init() {
  # Default keymap
  bindkey '^D' delete-word
  # Vi insert/normal maps
  bindkey -M viins '^D' delete-word
  bindkey -M vicmd '^D' delete-word
}
###################

export EDITOR=$(which nvim)
set -o ignoreeof
eval "$(ip --brief -4 a | grep -v DOWN | cut -d / -f1 | sed -e 's/-/_/g' | awk '{printf "export %s=%s; ",$1,$3}')"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
#ff -c /usr/share/fastfetch/presets/neofetch.jsonc

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
